### ISSUE TITLE
cannot make it work ubuntu

### ISSUE THREAD

**Issue by dcrystalj** [dorian-marchal/bing-daily-wallpaper#4]
i get error like this in ubuntu 15.10:

```
➜  ~  bing-daily-wallpaper

/usr/local/lib/node_modules/bing-daily-wallpaper/bin/bing-daily-wallpaper:34
            throw err;
                  ^
Error: Error while downloading the wallpaper at http://www.bing.com/az/hprichbg/rb/StoatWinter_ROW11086894844_1920x1080.jpg
    at /usr/local/lib/node_modules/bing-daily-wallpaper/node_modules/daily-wallpaper/lib/daily-wallpaper.js:55:33
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/bing-daily-wallpaper/node_modules/daily-wallpaper/lib/daily-wallpaper.js:93:28)
    at WriteStream.EventEmitter.emit (events.js:117:20)
    at WriteStream.<anonymous> (fs.js:1660:12)
    at Object.oncomplete (fs.js:107:15)

```

and if i specify /tmp folder

```
➜  ~  bing-daily-wallpaper --directory /tmp

/usr/local/lib/node_modules/bing-daily-wallpaper/bin/bing-daily-wallpaper:34
            throw err;
                  ^
Error: Error while setting the wallpaper from /tmp/2016-01-08.jpg
    at /usr/local/lib/node_modules/bing-daily-wallpaper/node_modules/daily-wallpaper/lib/daily-wallpaper.js:60:37
    at /usr/local/lib/node_modules/bing-daily-wallpaper/node_modules/daily-wallpaper/node_modules/wallpaper/node_modules/linux-wallpaper/index.js:170:4
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

```

**Comment by jgillich** [comment]
This is an issue in `daily-wallpaper`, it just throws away the original error for this completely unhelpful message. It still works though, at least for me.

**Comment by dcrystalj** [comment]
i ended up with setting crontab with python script.
