### ISSUE TITLE
Problems on kde neon 5.9 with plasma desktop

### ISSUE THREAD

**Issue by ivan0013** [dorian-marchal/bing-daily-wallpaper#7]
Here is the output. I get the image downloaded on the right folder, then, it fails.
```
Wallpaper updated.
/usr/lib/node_modules/bing-daily-wallpaper/bin/bing-daily-wallpaper:34
            throw err;
            ^

Error: Error while setting the wallpaper from /home/ivan/.bing-wallpapers/2017-03-07.jpg
    at /usr/lib/node_modules/bing-daily-wallpaper/node_modules/daily-wallpaper/lib/daily-wallpaper.js:60:37
    at /usr/lib/node_modules/bing-daily-wallpaper/node_modules/linux-wallpaper/index.js:170:4
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

```

**Comment by frdrcv** [comment]
I have the same problem on KDE Neon.

**Comment by dorian-marchal** [comment]
It should be fixed on the latest version.
